const menuItems = [
  {
    title: "MENU",
    items: [
      {
        icon: "/home.png",
        label: "Dashboard",
        href: "/admin/dashboard",
        visible: ["admin"],
      },
      {
        icon: "/home.png",
        label: "Home",
        href: "/",
        visible: ["teacher", "student", "parent"],
      },
      {
        icon: "/teacher.png",
        label: "Teachers",
        href: "/admin/teachers",
        visible: ["admin"],
      },
      {
        icon: "/student.png",
        label: "Students",
        href: "/admin/students",
        visible: ["admin"],
      },
      {
        icon: "/parent.png",
        label: "Parents",
        href: "/admin/parents",
        visible: ["admin"],
      },
      {
        icon: "/subject.png",
        label: "Subjects",
        href: "/admin/subjects",
        visible: ["admin"],
      },
      {
        icon: "/class.png",
        label: "Classes",
        href: "/admin/classes",
        visible: ["admin"],
      },
      {
        icon: "/class.png",
        label: "Classes",
        href: "/teacher/classes",
        visible: ["teacher"],
      },
      {
        icon: "/lesson.png",
        label: "Lessons",
        href: "/admin/lessons",
        visible: ["admin"],
      },
      {
        icon: "/exam.png",
        label: "Exams",
        href: "/list/exams",
        visible: ["admin", "teacher", "student", "parent"],
      },
      {
        icon: "/assignment.png",
        label: "Assignments",
        href: "/teacher/assignments",
        visible: ["teacher"],
      },
      {
        icon: "/assignment.png",
        label: "Assignments",
        href: "/list/assignments",
        visible: ["student", "parent"],
      },
      {
        icon: "/result.png",
        label: "Results",
        href: "/admin/exam-config",
        visible: ["admin"],
      },
      {
        icon: "/result.png",
        label: "Results",
        href: "/teacher/marksheets",
        visible: ["teacher"],
      },
      {
        icon: "/result.png",
        label: "Results",
        href: "/parent/results",
        visible: ["parent"],
      },
      {
        icon: "/result.png",
        label: "Results",
        href: "/list/results",
        visible: ["student"],
      },
      {
        icon: "/attendance.png",
        label: "Attendance",
        href: "/admin/attendance-reports",
        visible: ["admin"],
      },
      {
        icon: "/attendance.png",
        label: "Attendance",
        href: "/teacher/attendance",
        visible: ["teacher"],
      },
      {
        icon: "/attendance.png",
        label: "Attendance",
        href: "/parent/attendance",
        visible: ["parent"],
      },
      {
        icon: "/calendar.png",
        label: "Events",
        href: "/list/events",
        visible: ["admin", "teacher", "student", "parent"],
      },
      {
        icon: "/message.png",
        label: "Messages",
        href: "/list/messages",
        visible: ["admin", "teacher", "student", "parent"],
      },
      {
        icon: "/announcement.png",
        label: "Sound Alerts",
        href: "/admin/security-alerts",
        visible: ["admin"],
      },
    ],
  },
  {
    title: "OTHER",
    items: [
      {
        icon: "/profile.png",
        label: "Profile",
        href: "/admin/dashboard",
        visible: ["admin"],
      },
      {
        icon: "/profile.png",
        label: "Profile",
        href: "/profile",
        visible: ["teacher", "student", "parent"],
      },
      {
        icon: "/setting.png",
        label: "Settings",
        href: "/admin/settings",
        visible: ["admin"],
      },
      {
        icon: "/setting.png",
        label: "Settings",
        href: "/teacher/settings",
        visible: ["teacher"],
      },
      {
        icon: "/setting.png",
        label: "Settings",
        href: "/parent/settings",
        visible: ["parent"],
      },
      {
        icon: "/setting.png",
        label: "Settings",
        href: "/settings",
        visible: ["student"],
      },
      {
        icon: "/logout.png",
        label: "Logout",
        href: "/logout",
        visible: ["admin", "teacher", "student", "parent"],
      },
    ],
  },
];
