import { Buffer } from 'node:buffer';

const XLSX = require('xlsx');
import { ADMISSION_DEMO_ROWS } from './demoSeed';

export type AdmissionWorkbookRow = Record<string, any>;

export type AdmissionTemplateRow = {
  'Student Name': string;
  'Parent Name': string;
  'Parent Email': string;
  'Parent Phone': string;
  Address: string;
  Occupation: string;
  'Class ID': string;
  'Academic Year': string;
  'Date of Birth': string;
  'Parent NID Number': string;
  'Birth Certificate Number': string;
  'Parent NID File': string;
  'Birth Certificate File': string;
};

export function normalizeWorkbookCell(value: unknown) {
  return String(value ?? '').trim();
}

export function parseExcelDate(raw: any): string {
  if (!raw) return '';

  if (raw instanceof Date && !Number.isNaN(raw.getTime())) {
    return raw.toISOString().slice(0, 10);
  }

  if (typeof raw === 'number') {
    const excelDate = XLSX.SSF.parse_date_code(raw);
    if (excelDate) {
      const d = new Date(excelDate.y, excelDate.m - 1, excelDate.d, 9, 0, 0, 0);
      if (!Number.isNaN(d.getTime())) {
        return d.toISOString().slice(0, 10);
      }
    }
  }

  const text = String(raw).trim();
  if (!text) return '';

  const direct = text.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (direct) {
    return `${direct[1]}-${direct[2]}-${direct[3]}`;
  }

  const parsed = new Date(text);
  if (!Number.isNaN(parsed.getTime())) {
    return parsed.toISOString().slice(0, 10);
  }

  const m = text.match(/(\d{1,2})[/-](\d{1,2})[/-](\d{2,4})/);
  if (m) {
    const day = Number(m[1]);
    const month = Number(m[2]);
    let year = Number(m[3]);
    if (year < 100) {
      year += year >= 50 ? 1900 : 2000;
    }

    const candidate = new Date(year, month - 1, day, 9, 0, 0, 0);
    if (!Number.isNaN(candidate.getTime())) {
      return candidate.toISOString().slice(0, 10);
    }
  }

  return '';
}

export function parseAdmissionWorkbook(buffer: Buffer) {
  const workbook = XLSX.read(buffer, { type: 'buffer', cellDates: true });
  const firstSheet = workbook.SheetNames[0];

  if (!firstSheet) {
    return [] as AdmissionWorkbookRow[];
  }

  return XLSX.utils.sheet_to_json(workbook.Sheets[firstSheet], {
    defval: '',
    raw: false,
  }) as AdmissionWorkbookRow[];
}

export function buildAdmissionTemplateWorkbook() {
  const workbook = XLSX.utils.book_new();

  const rows: AdmissionTemplateRow[] = ADMISSION_DEMO_ROWS as AdmissionTemplateRow[];

  const admissionsSheet = XLSX.utils.json_to_sheet(rows);
  XLSX.utils.book_append_sheet(workbook, admissionsSheet, 'Admissions');

  const instructions = XLSX.utils.aoa_to_sheet([
    ['Admission Intake Template'],
    [''],
    ['Use this sheet to import admission data. Keep file names in the last two columns exactly the same as the uploaded document file names.'],
    ['OCR will scan the NID and birth-certificate images, verify them against the row data, and create the existing XML structure after verification.'],
    ['Roll numbers are generated by the system. Do not type or change them manually.'],
    ['If your school does not use kg-A, replace the Class ID values with an existing class code before importing.'],
    ['If you do not have real scans for testing, open the Admission Intake screen and use Load demo documents.'],
    [''],
    ['Required columns:'],
    ['Student Name', 'Parent Name', 'Parent Email', 'Class ID', 'Academic Year', 'Date of Birth', 'Parent NID File', 'Birth Certificate File'],
    [''],
    ['Optional columns:'],
    ['Parent Phone', 'Address', 'Occupation', 'Parent NID Number', 'Birth Certificate Number'],
  ]);

  XLSX.utils.book_append_sheet(workbook, instructions, 'Instructions');

  return workbook;
}
